import { Product, Category, Article, FAQItem } from '@/types';

export const DOMAIN = 'https://elfify.ir';
export const PHONE_NUMBER = '+98 992 868 1254';
export const PHONE_RAW = '09928681254';
export const STORE_NAME = 'فروشگاه تخصصی دزدگیر اماکن و تجهیزات هوشمند ELFify';
export const STORE_NAME_EN = 'ELFify Security & Smart IoT Systems';
export const ADDRESS_FA = 'تهران، خیابان جمهوری، تقاطع فردوسی، مرکز تجارت الکترونیک و تجهیزات حفاظتی الفیفای، پلاک ۱۲۴';
export const ADDRESS_EN = 'No. 124, Security & Electronics Commerce Center, Jomhouri St., Tehran, Iran';
export const EMAIL = 'info@elfify.ir';
export const POSTAL_CODE = '1136845912';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    slug: 'alarm-panels',
    name: 'پنل‌های دزدگیر سیم‌کارتی و خط ثابت',
    nameEn: 'GSM & Landline Alarm Panels',
    description: 'انواع مرکز کنترل دزدگیر هوشمند سیم کارتی با رله‌های کنترل خروجی و پشتیبانی از زون‌های بیسیم و باسیم',
    descriptionEn: 'Smart GSM alarm central hubs with phone dialer, wireless zones, and smart mobile apps',
    iconName: 'ShieldAlert',
    itemCount: 14,
    featuredImage: '/example_product.webp',
  },
  {
    id: 'cat-2',
    slug: 'sensors-detectors',
    name: 'چشمی و سنسورهای حرکتی و وزنی',
    nameEn: 'PIR Motion & Pet Immune Sensors',
    description: 'سنسورهای راداری، چشمی مادون قرمز (PIR)، مگنت درب و پنجره، دتکتور دود و شکست شیشه',
    descriptionEn: 'PIR motion detectors, pet-immune sensors, magnetic door contacts, and glass break detectors',
    iconName: 'Eye',
    itemCount: 28,
    featuredImage: '/example_product.webp',
  },
  {
    id: 'cat-3',
    slug: 'iot-smart-home',
    name: 'تجهیزات اینترنت اشیاء (IoT) و رله‌های کنترل',
    nameEn: 'Smart IoT Controllers & Smart Relays',
    description: 'رله‌های هوشمند پیامکی و وای‌فای، کنترل روشنایی، پمپ آب، کرکره برقی و تجهیزات هوشمندسازی خانه',
    descriptionEn: 'WiFi/GSM IoT smart relays, home automation modules, remote appliance switch controllers',
    iconName: 'Cpu',
    itemCount: 19,
    featuredImage: '/example_product.webp',
  },
  {
    id: 'cat-4',
    slug: 'sirens-strobes',
    name: 'بلندگو، آژیر و کاور ضد سرقت',
    nameEn: 'Sirens, Speakers & Security Enclosures',
    description: 'بلندگوهای ۳۰ وات، پیزو الکتریک، آژیرهای فلاشر‌دار، کاورهای فلزی محافظتی با تمپر',
    descriptionEn: 'Outdoor 30W sirens, indoor piezo alarms, strobe lights, and tamper-protected metal boxes',
    iconName: 'BellRing',
    itemCount: 12,
    featuredImage: '/example_product.webp',
  },
  {
    id: 'cat-5',
    slug: 'security-packages',
    name: 'پکیج‌های کامل آماده نصب',
    nameEn: 'Ready-to-Install Security Kits',
    description: 'بسته‌های اقتصادی و VIP دزدگیر اماکن شامل پنل مرکزی، باتری، چشمی، بلندگو و ریموت کنترل',
    descriptionEn: 'Complete home and shop alarm bundles with sensors, battery, remotes, and sirens included',
    iconName: 'PackageCheck',
    itemCount: 8,
    featuredImage: '/example_product.webp',
  },
  {
    id: 'cat-6',
    slug: 'batteries-power',
    name: 'باتری اضطراری و منبع تغذیه',
    nameEn: 'Backup Batteries & Power Supplies',
    description: 'باتری‌های سیلد لید اسید ۱۲ ولت ۴.۵ و ۷.۲ آمپر ویژه کارکرد دزدگیر هنگام قطعی برق',
    descriptionEn: '12V 4.5Ah and 7.2Ah SLA backup batteries and high efficiency power adapters',
    iconName: 'BatteryCharging',
    itemCount: 9,
    featuredImage: '/example_product.webp',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p-101',
    slug: 'iomax-plus-lite-iot-alarm',
    name: 'پنل مرکزی دزدگیر اماکن سیم کارتی ioMax-Plus مدل Lite',
    nameEn: 'ioMax-Plus Lite GSM IoT Smart Security Hub',
    category: 'پنل‌های دزدگیر سیم‌کارتی و خط ثابت',
    categorySlug: 'alarm-panels',
    price: 6450000,
    originalPrice: 7800000,
    discountPercent: 17,
    inStock: true,
    stockCount: 15,
    sku: 'ELF-IOMAX-LITE',
    gtin: '6261234567890',
    brand: 'ioMax',
    ratingValue: 4.9,
    reviewCount: 38,
    shortDescription: 'مرکز دزدگیر و اینترنت اشیاء ioMax-Plus Lite مجهز به مودم GSM پیشرفته، ۴ زون باسیم، پشتیبانی از ۳۰ سنسور بیسیم و اپلیکیشن اختصاصی فارسی.',
    shortDescriptionEn: 'ioMax-Plus Lite GSM & IoT Security central panel with 4 wired zones, 30 wireless sensor capacity, and dedicated cloud mobile app.',
    description: 'پنل دزدگیر اماکن هوشمند ioMax-Plus مدل Lite یک سیستم پیشرفته حفاظتی و کنترل تجهیزات بر مبنای اینترنت اشیاء (IoT) است. این دستگاه دارای پردازنده پرسرعت ARM با ریموت‌های ضد هک Hopping Code بوده و به محض تحریک هر یک از زون‌ها، کمتر از ۲ ثانیه از طریق پیامک و تماس تلفنی وقوع هشدار را با نام دقیق زون گزارش می‌دهد.',
    descriptionEn: 'The ioMax-Plus Lite is an ultra-fast IoT security hub designed for residences, offices, and warehouses. It provides real-time SMS/Call alerts, remote appliance controls, and tamper resistance.',
    images: ['/example_product.webp'],
    features: [
      'پشتیبانی هم‌زمان از سیم‌کارت همراه اول، ایرانسل و رایتل',
      '۴ زون مجزای باسیم با قابلیت نام‌گذاری دلخواه + ۳۰ سنسور بیسیم',
      'دارای ۲ خروجی رله قابل کنترل با موبایل جهت روشن/خاموش کردن روشنایی و وسایل برقی',
      'سرعت ارسال گزارش هشدار زیر ۲ ثانیه با تماس صوتی و پیامک فارسی',
      'پشتیبانی از نرم‌افزار اندروید و iOS با رابط کاربری شیک و سریع',
      'ریموت‌های Hopping Code با فرکانس 433 مگاهرتز غیرقابل کپی',
      'سیستم اعلام قطع برق شهر، سوختن فیوز و کم شدن شارژ باتری',
    ],
    featuresEn: [
      'Dual GSM & SMS dialer with lightning fast sub-2s trigger response',
      '4 wired configurable zones + support for 30 wireless sensors',
      '2 built-in controllable IoT relays for lights & smart home switches',
      'Full iOS & Android remote management apps',
      'Hopping code remotes immune to frequency grabbing',
      'AC power outage and low battery real-time alerts',
    ],
    specs: {
      'تعداد زون باسیم': '۴ زون (NC / NO)',
      'تعداد زون بیسیم': '۳۰ سنسور با کدینگ اختصاصی',
      'نوع ریموت': 'هاپینگ کد ۴۳۳ مگاهرتز (Hopping Code)',
      'تعداد رله‌های خروجی': '۲ رله مجزا ۱۰ آمپر',
      'قابلیت شنود محیط': 'دارد (میکروفون فوق حساس داخلی)',
      'حافظه تلفن کننده': '۲۰ شماره تلفن همراه و ثابت',
      'ولتاژ کاری': '۲۲۰ ولت متناوب / باتری ۱۲ ولت ۷ آمپر',
      'گارانتی': '۳۶ ماه ضمانت طلایی تعویض الفیفای',
    },
    specsEn: {
      'Wired Zones': '4 Zones (NC/NO)',
      'Wireless Capacity': 'Up to 30 sensors',
      'Remote Encryption': 'Hopping Code 433.92 MHz',
      'Controllable Relays': '2 Relay outputs (10A)',
      'Audio Monitoring': 'Yes (Integrated high sensitivity mic)',
      'Phonebook Memory': '20 Contact numbers',
      'Operating Voltage': '220V AC / 12V DC Battery',
      'Warranty': '36 Months Official ELFify Replacement Guarantee',
    },
    isFeatured: true,
    isNew: true,
    hasFreeShipping: true,
    packageType: 'Lite',
    faqs: [
      {
        question: 'آیا در صورت قطع اینترنت یا برق، دستگاه کار می‌کند؟',
        answer: 'بله، دستگاه دارای باتری پشتیبان داخلی بوده و حتی در صورت قطعی اینترنت، کلیه هشدارها و دستورات را از طریق شبکه دکل‌های موبایل (GSM / پیامک و تماس) بدون وقفه ارسال می‌کند.'
      },
      {
        question: 'چند ریموت و چشمی بیسیم را می‌توان به ioMax-Plus Lite متصل کرد؟',
        answer: 'شما می‌توانید تا ۱۰ ریموت مجزا و تا ۳۰ سنسور حرکتی، مگنت، دتکتور دود و پدال بیسیم را به این پنل متصل و برای هرکدام پیامک اختصاصی تعریف نمایید.'
      }
    ],
    faqsEn: [
      {
        question: 'Does it work if electricity or internet goes down?',
        answer: 'Yes! The backup battery maintains power for over 48 hours, and alerts are immediately dispatched via GSM phone call and SMS cellular network.'
      }
    ],
  },
  {
    id: 'p-102',
    slug: 'silex-sg8-s-alarm-system',
    name: 'دزدگیر اماکن سیم‌کارتی سایلکس مدل SG8-S',
    nameEn: 'Silex SG8-S Dual SIM & Landline Alarm Central',
    category: 'پنل‌های دزدگیر سیم‌کارتی و خط ثابت',
    categorySlug: 'alarm-panels',
    price: 8600000,
    originalPrice: 9400000,
    discountPercent: 9,
    inStock: true,
    stockCount: 8,
    sku: 'SIL-SG8S',
    gtin: '6269876543210',
    brand: 'Silex',
    ratingValue: 4.8,
    reviewCount: 54,
    shortDescription: 'پنل سایلکس SG8-S دارای ۴ زون باسیم و ۱ زون بیسیم، پشتیبانی از سیم‌کارت و خط تلفن ثابت با تلفن‌کننده سخنگو.',
    shortDescriptionEn: 'Silex SG8-S security hub with speech dialer, dual SIM/landline support, and 4 wired zones.',
    description: 'دزدگیر اماکن سایلکس مدل SG8-S از نام‌آشناترین و پایدارترین پنل‌های حفاظتی کشور است. این سیستم مجهز به سیستم تلفن‌کننده پیشرفته با صدای گویای فارسی بوده و ۴ رله خروجی را در اختیار کاربر قرار می‌دهد.',
    descriptionEn: 'The legendary Silex SG8-S offers unmatched stability, voice speech alerts, and remote multi-relay controls.',
    images: ['/example_product.webp'],
    features: [
      'دارای ۵ زون با قابلیت تعریف به ۸ حالت مختلف',
      'پشتیبانی همزمان از خط ثابت و سیم‌کارت',
      '۴ رله خروجی مجزا با تنظیم حالت‌های مختلف (لحظه‌ای، پایدار، درب بازکن)',
      'ثبت ۹۹ واقعه اخیر با تاریخ و ساعت دقیق',
      'ارسال گزارش قطع برق و وصل برق شهر به همراه گزارش قطع بلندگو',
    ],
    featuresEn: [
      '5 versatile security zones with 8 mode configurations',
      'Dual line: SIM card + PSTN landline failover',
      '4 programmable relays for home automation',
      '99 event log history with timestamp',
      'Speaker line tampering & AC power loss notification',
    ],
    specs: {
      'تعداد زون': '۵ زون با تنظیمات اختصاصی',
      'خروجی رله': '۴ رله مستقل',
      'ریموت': 'سایلکس لنکس Hopping Code',
      'گارانتی': '۲۴ ماه گارانتی رسمی سایلکس',
    },
    specsEn: {
      'Zones': '5 customizable zones',
      'Relays': '4 independent relays',
      'Remote': 'Silex Lenox Hopping Code',
      'Warranty': '24 Months Silex Official Warranty',
    },
    isFeatured: true,
    hasFreeShipping: true,
    packageType: 'Pro',
    faqs: [
      {
        question: 'آیا رله‌های سایلکس می‌توانند درب پارکینگ یا روشنایی را باز و بسته کنند؟',
        answer: 'بله، خروجی‌های رله دستگاه از طریق اپلیکیشن یا ارسال کد SMS می‌توانند درب بازکن، پمپ، چراغ یا هر وسیله برقی را کنترل کنند.'
      }
    ]
  },
  {
    id: 'p-103',
    slug: 'firewall-f10-gsm-alarm',
    name: 'دزدگیر اماکن فایروال مدل F10 سیم کارتی با رله خروجی',
    nameEn: 'Firewall F10 GSM Security System with 7 Output Relays',
    category: 'پنل‌های دزدگیر سیم‌کارتی و خط ثابت',
    categorySlug: 'alarm-panels',
    price: 9200000,
    originalPrice: 10100000,
    discountPercent: 9,
    inStock: true,
    stockCount: 11,
    sku: 'FIR-F10-GSM',
    gtin: '6265432109876',
    brand: 'Firewall',
    ratingValue: 4.9,
    reviewCount: 42,
    shortDescription: 'دزدگیر فایروال F10 دارای ۸ زون باسیم و ۸ زون بیسیم، ۷ رله خروجی، صفحه نمایش LCD فارسی و سیستم سخنگو.',
    shortDescriptionEn: 'Firewall F10 featuring 8 wired & 8 wireless zones, 7 smart relays, and Persian LCD display.',
    description: 'دستگاه مرکزی فایروال F10 غول حفاظتی ساختمان است که با ۷ رله خروجی امکان هوشمندسازی تمام بخش‌های خانه یا باغ را فراهم می‌آورد. این دستگاه مجهز به مدار تست باتری هوشمند و شنود صدای محیط بسیار پرقدرت است.',
    descriptionEn: 'Firewall F10 is the ultimate security and home automation powerhouse equipped with 7 output relays and 8 wired zones.',
    images: ['/example_product.webp'],
    features: [
      '۸ زون باسیم و ۸ زون بیسیم با قابلیت تفکیک کامل',
      '۷ رله خروجی قدرتمند جهت کنترل روشنایی، کولر، پکیج و شیر برقی',
      'صفحه نمایشگر LCD فارسی با منوی تنظیمات فوق‌العاده ساده',
      'سخنگوی فارسی دو طرفه و قابلیت ضبط ۲۲ پیام صوتی مجزا',
      'دارای میکروفون داخلی قوی جهت شنود صدای محیط',
    ],
    featuresEn: [
      '8 wired + 8 wireless zones with independent zone naming',
      '7 high-power relays to automate AC, heaters, water valves & lights',
      'Persian LCD display interface with intuitive menus',
      'Bidirectional speech dialer with 22 distinct voice message slots',
      'High sensitivity environmental audio microphone',
    ],
    specs: {
      'تعداد زون باسیم': '۸ زون مستقل',
      'تعداد زون بیسیم': '۸ زون با کد اختصاصی',
      'رله خروجی': '۷ رله',
      'گارانتی': '۶۰ ماه (۵ سال) گارانتی رسمی فایروال',
    },
    specsEn: {
      'Wired Zones': '8 zones',
      'Wireless Zones': '8 zones',
      'Relays': '7 Relays',
      'Warranty': '60 Months Official Firewall Warranty',
    },
    isFeatured: true,
    hasFreeShipping: true,
    packageType: 'Plus',
  },
  {
    id: 'p-104',
    slug: 'classic-z4-ultra-64bit-gsm',
    name: 'دزدگیر اماکن کلاسیک مدل Z4 Ultra 64Bit به همراه تلفن کننده G1 Ultra',
    nameEn: 'Classic Z4 Ultra 64-Bit Alarm Hub with G1 Ultra GSM Dialer',
    category: 'پنل‌های دزدگیر سیم‌کارتی و خط ثابت',
    categorySlug: 'alarm-panels',
    price: 10400000,
    originalPrice: 11500000,
    discountPercent: 10,
    inStock: true,
    stockCount: 6,
    sku: 'CLS-Z4U-G1',
    brand: 'Classic',
    ratingValue: 4.9,
    reviewCount: 61,
    shortDescription: 'پکیج پنل مرکزی کلاسیک Z4 الترا ۶۴ بیت با ریموت‌های ترارکد و تلفن‌کننده سیم‌کارتی G1 الترا، معتبرترین برند حفاظتی ایران.',
    shortDescriptionEn: 'Classic Z4 Ultra with G1 Ultra cellular communicator and anti-clone TeraCode encryption.',
    description: 'کلاسیک Z4 Ultra با کدگذاری پیشرفته ۶۴ بیتی ترارکد نهایت ایمنی در برابر دستگاه‌های کپی ریموت را ایجاد می‌کند. همراهی آن با تلفن‌کننده هوشمند G1 Ultra امکان ارسال پیامک و برقراری تماس سریع را فراهم می‌سازد.',
    descriptionEn: 'The gold standard in Iranian electronic security with 64-bit anti-clone remote protection.',
    images: ['/example_product.webp'],
    features: [
      'سیستم رمزنگاری اختصاصی ۶۴ بیتی TeraCode ضد هک',
      'تلفن‌کننده سیم‌کارتی G1 Ultra با گزارش دقیق اتفاقات',
      'قابلیت کنترل ۴ وسیله برقی از راه دور با اپلیکیشن',
      'سازگاری کامل با تمامی مگنت‌ها و چشمی‌های باسیم و بیسیم',
    ],
    featuresEn: [
      '64-bit TeraCode military-grade encryption',
      'G1 Ultra GSM module with comprehensive event logging',
      '4 remote electric device switches via mobile app',
      'Broad compatibility with all wired & wireless detectors',
    ],
    specs: {
      'تعداد زون': '۴ زون باسیم + ۱ زون بیسیم',
      'فرکانس ریموت': '۴۳۳.۹۲ مگاهرتز ترارکد ۶۴ بیت',
      'گارانتی': '۲۴ ماه گارانتی الکترونیک کلاسیک',
    },
    specsEn: {
      'Zones': '4 Wired + 1 Wireless',
      'Frequency': '433.92 MHz TeraCode',
      'Warranty': '24 Months Classic Electronics Warranty',
    },
    isFeatured: true,
    hasFreeShipping: true,
    packageType: 'Pro',
  },
  {
    id: 'p-105',
    slug: 'wireless-pir-motion-sensor-pet-immune',
    name: 'چشمی بیسیم دزدگیر اماکن وزنی (ضد حیوانات) مدل Pet-30',
    nameEn: 'Pet-Immune Wireless PIR Motion Detector (Up to 30KG)',
    category: 'چشمی و سنسورهای حرکتی و وزنی',
    categorySlug: 'sensors-detectors',
    price: 980000,
    originalPrice: 1200000,
    discountPercent: 18,
    inStock: true,
    stockCount: 45,
    sku: 'SEN-PET30-WL',
    brand: 'ioMax',
    ratingValue: 4.7,
    reviewCount: 29,
    shortDescription: 'سنسور حرکتی بیسیم با قابلیت تشخیص حیوانات خانگی تا وزن ۳۰ کیلوگرم، بدون آژیر خطا در شب و با زاویه پوشش ۱۱۰ درجه.',
    shortDescriptionEn: 'Wireless pet-immune PIR sensor ignoring pets up to 30kg with 110-degree wide angle coverage.',
    description: 'چشمی وزنی بیسیم مدل Pet-30 مجهز به دو سنسور مادون قرمز مجزا و الگوریتم فیلتر دیجیتال است که از ارسال آژیر بی‌دلیل بر اثر عبور گربه، سگ و پرندگان تا وزن ۳۰ کیلوگرم کاملاً جلوگیری می‌کند.',
    descriptionEn: 'Dual pyroelectric element design that eliminates false alarms caused by domestic pets under 30kg.',
    images: ['/example_product.webp'],
    features: [
      'مصونیت از تحریک حیوانات خانگی و پرندگان تا ۳۰ کیلوگرم',
      'برد دید مفید تا ۱۲ متر با زاویه باز ۱۱۰ درجه',
      'سیستم مصرف انرژی فوق‌العاده بهینه با باتری نیم‌قلمی با طول عمر بیش از ۱ سال',
      'فرکانس ۴۳۳ مگاهرتز سازگار با انواع دزدگیرهای ایرانی و خارجی',
    ],
    featuresEn: [
      'Pet immunity up to 30 kg',
      '12m detection range with 110° wide beam',
      'Ultra low power consumption (>1 year battery life)',
      '433MHz frequency universally compatible',
    ],
    specs: {
      'زاویه دید': '۱۱۰ درجه افقی و ۶۰ درجه عمودی',
      'فاصله آشکارسازی': '۱۲ متر مفید',
      'تغذیه': '۲ عدد باتری نیم‌قلمی AAA',
      'فرکانس': '۴۳۳ مگاهرتز',
    },
    specsEn: {
      'Coverage': '110° Horizontal / 60° Vertical',
      'Range': '12 meters',
      'Battery': '2x AAA Alkaline',
      'Frequency': '433.92 MHz',
    },
    hasFreeShipping: false,
    packageType: 'Standard',
  },
  {
    id: 'p-106',
    slug: 'iot-smart-relay-4ch-gsm-wifi',
    name: 'ماژول رله کنترل هوشمند ۴ کانال GSM و Wi-Fi اینترنت اشیاء',
    nameEn: '4-Channel Smart IoT GSM & WiFi Relay Controller',
    category: 'تجهیزات اینترنت اشیاء (IoT) و رله‌های کنترل',
    categorySlug: 'iot-smart-home',
    price: 2850000,
    originalPrice: 3300000,
    discountPercent: 14,
    inStock: true,
    stockCount: 22,
    sku: 'IOT-RLY-4CH',
    brand: 'ELFify IoT',
    ratingValue: 5.0,
    reviewCount: 19,
    shortDescription: 'کنترل‌کننده رله ۴ کاناله ۱۰ آمپر جهت خاموش و روشن کردن موتور پمپ، روشنایی ویلا، کولر و وسایل برقی از هر کجای دنیا با اینترنت یا پیامک.',
    shortDescriptionEn: '4-channel smart relay module for home automation, smart garden irrigation, and lighting management via App or SMS.',
    description: 'دستگاه کنترل رله ۴ کاناله ELFify IoT ابزاری بی‌نظیر برای هوشمندسازی باغ‌ها، ویلاها، کارگاه‌ها و منازل است. هر کانال دارای حالت‌های لحظه‌ای، دائم، زمان‌بندی هفتگی و سناریوهای خودکار است.',
    descriptionEn: 'The ELFify 4-channel IoT relay allows you to control electrical appliances, irrigation pumps, gates, and heaters from anywhere in the world.',
    images: ['/example_product.webp'],
    features: [
      '۴ رله خروجی پرقدرت ۱۰ آمپر با ایزولاسیون کامل اپتوکوپلر',
      'پشتیبانی دوگانه از اتصال وای‌فای خانگی و سیم‌کارت موبایل',
      'تایمر و زمان‌بندی خودکار هفتگی بدون نیاز به اینترنت دائم',
      'سنسور دمای محیط با قابلیت تعریف سناریوی ترموستات هوشمند',
    ],
    featuresEn: [
      '4 high-capacity 10A relays with optocoupler isolation',
      'Dual GSM SIM & WiFi connectivity',
      'Offline weekly scheduling & smart timers',
      'Optional temperature sensor with smart thermostat triggers',
    ],
    specs: {
      'تعداد کانال': '۴ رله مجزا',
      'حداکثر جریان هر رله': '۱۰ آمپر (۲۲۰۰ وات)',
      'ارتباط': 'Wi-Fi 2.4GHz + GSM 2G/4G',
      'گارانتی': '۲۴ ماه تعویض بی‌قیدوشرط',
    },
    specsEn: {
      'Channels': '4 Isolated Relays',
      'Max Load': '10A per channel (2200W)',
      'Connectivity': 'WiFi 2.4GHz + GSM SIM',
      'Warranty': '24 Months Replacement Warranty',
    },
    isFeatured: true,
    hasFreeShipping: true,
    packageType: 'Plus',
  },
  {
    id: 'p-107',
    slug: 'outdoor-siren-strobe-30w-tamper',
    name: 'بلندگو شیپوری ۳۰ وات ضد آب به همراه کاور فلزی و تمپر ضد برش',
    nameEn: '30W Waterproof Horn Siren with Metal Cover & Anti-Tamper Switch',
    category: 'بلندگو، آژیر و کاور ضد سرقت',
    categorySlug: 'sirens-strobes',
    price: 890000,
    originalPrice: 1050000,
    discountPercent: 15,
    inStock: true,
    stockCount: 30,
    sku: 'SIR-SPK-30W',
    brand: 'ioMax',
    ratingValue: 4.8,
    reviewCount: 31,
    shortDescription: 'پکیج بلندگوی ۳۰ وات پرقدرت ۱۲۰ دسی‌بل با پرتاب صدای عالی، کاور فلزی ضخیم رنگ کوره‌ای و سوئیچ تمپر ضد تخریب.',
    shortDescriptionEn: '30W high power 120dB outdoor horn speaker with weather-resistant tamper-protected metal housing.',
    description: 'برای ایجاد بازدارندگی صوتی قوی در برابر سارقین، بلندگوی ۳۰ وات الفیفای با کاور فلزی مقاوم در برابر ضربه و باران بهترین گزینه است. سوئیچ تمپر در صورت تلاش سارق برای باز کردن کاور بلافاصله پنل را فعال می‌کند.',
    descriptionEn: 'Heavy-duty 30W outdoor siren delivering ear-piercing 120dB deterrence with tamper detection.',
    images: ['/example_product.webp'],
    features: [
      'قدرت پرتاب صدای ۱۲۰ دسی‌بل با وضوح فوق‌العاده',
      'کاور فلزی استاندارد با رنگ الکترواستاتیک ضد زنگ',
      'سوئیچ تمپر داخلی متصل به زون ۲۴ ساعته جهت جلوگیری از تخریب',
      'ضد آب و مقاوم در برابر نور شدید خورشید و گرد و غبار',
    ],
    featuresEn: [
      '120dB high-decibel acoustic deterrence',
      'Electrostatic powder-coated rustproof metal enclosure',
      'Integrated tamper switch connected to 24h tamper zone',
      'IP65 weather resistant',
    ],
    specs: {
      'توان خروجی': '۳۰ وات واقعی',
      'شدت صدا': '۱۲۰ دسی‌بل در فاصله ۱ متر',
      'جنس بدنه کاور': 'ورق فولادی ۱ میلی‌متر',
      'مقاومت در برابر آب': 'IP65',
    },
    specsEn: {
      'Output Power': '30 Watts True RMS',
      'Sound Pressure': '120dB @ 1m',
      'Cover Material': '1mm Steel with powder coating',
      'Protection Rating': 'IP65',
    },
    hasFreeShipping: false,
    packageType: 'Standard',
  },
  {
    id: 'p-108',
    slug: 'sla-battery-12v-7-2ah-security',
    name: 'باتری خشک سیلد لید اسید ۱۲ ولت ۷.۲ آمپر ویژه دزدگیر اماکن',
    nameEn: '12V 7.2Ah SLA High-Discharge Security Backup Battery',
    category: 'باتری اضطراری و منبع تغذیه',
    categorySlug: 'batteries-power',
    price: 790000,
    originalPrice: 890000,
    discountPercent: 11,
    inStock: true,
    stockCount: 60,
    sku: 'BAT-12V-72AH',
    brand: 'Long Energy',
    ratingValue: 4.9,
    reviewCount: 44,
    shortDescription: 'باتری تاریخ جدید با ماندگاری شارژ تا ۴۸ ساعت هنگام قطعی برق، بدون نیاز به نگهداری و نشتی، سازگار با تمام پنل‌ها.',
    shortDescriptionEn: '12V 7.2Ah fresh-date maintenance-free backup battery providing up to 48 hours emergency runtime.',
    description: 'باتری ۱۲ ولت ۷.۲ آمپر ساعت با کیفیت ساخت ممتاز و جریان‌دهی پیوسته، تضمین‌کننده امنیت پایدار ساختمان شما در هنگام قطع عمدی یا تصادفی برق شهر است.',
    descriptionEn: 'High capacity 12V 7.2Ah deep cycle SLA battery designed specifically for continuous security panel backup.',
    images: ['/example_product.webp'],
    features: [
      'تاریخ تولید به‌روز و عمر مفید بیش از ۳ سال',
      'تأمین برق دزدگیر و چشمی‌ها تا ۴۸ ساعت پیوسته در قطعی برق',
      'بدنه ABS کامپکت ضد اشتعال و بدون نشتی اسید',
      'پشتیبانی از شارژ شناور (Float Charging) استاندارد',
    ],
    featuresEn: [
      'Fresh production date with 3+ years service life',
      'Up to 48h continuous backup during blackout',
      'Flame retardant ABS sealed casing',
      'Designed for standard float charging cycles',
    ],
    specs: {
      'ولتاژ نامی': '۱۲ ولت',
      'ظرفیت': '۷.۲ آمپر ساعت (7.2Ah)',
      'ابعاد': '۱۵۱ × ۶۵ × ۹۴ میلی‌متر',
      'وزن': '۲.۱ کیلوگرم',
    },
    specsEn: {
      'Nominal Voltage': '12V DC',
      'Capacity': '7.2 Ampere Hours',
      'Dimensions': '151 x 65 x 94 mm',
      'Weight': '2.1 kg',
    },
    hasFreeShipping: false,
    packageType: 'Standard',
  },
];

export const ARTICLES: Article[] = [
  {
    id: 'art-1',
    slug: 'how-to-wire-alarm-pir-motion-sensors',
    title: 'آموزش گام به گام سیم‌کشی چشمی دزدگیر اماکن و تست زون‌های باسیم',
    titleEn: 'Step-by-Step Guide to Wiring Alarm PIR Sensors & Zone Configuration',
    excerpt: 'راهنمای عملی نحوه اتصال پایه‌های NC، NO، TMP و تغذیه ۱۲ ولت چشمی‌های حرکتی به پنل دزدگیر و اصول عیب‌یابی قطعی سیم.',
    excerptEn: 'Practical guide on connecting NC, NO, Tamper and 12V power terminals of motion detectors to alarm panels.',
    content: `سیم‌کشی صحیح چشمی‌ها (PIR Sensors) اساسی‌ترین بخش در نصب یک سیستم دزدگیر اماکن بدون خطاست.

### ۱. نام‌گذاری و وظیفه هر ترمینال در چشمی باسیم:
هر چشمی استاندارد حداقل دارای ۶ ترمینال پیچی است:
- **+ و - (Power 12V DC):** تغذیه مثبت و منفی ۱۲ ولت از خروجی AUX پنل مرکزی.
- **ALARM (NC / Common):** خروجی رله سنسور که در حالت عادی بسته (Normally Closed) بوده و هنگام تشخیص حرکت باز می‌شود.
- **TAMPER (T / T):** میکروسوئیچ محافظتی بدنه که در صورت باز شدن قاب چشمی زون ۲۴ ساعته را تحریک می‌کند.

### ۲. نوع کابل استاندارد:
همیشه از کابل فویل‌دار تمام مس با ضخامت حداقل ۰.۵ یا ۰.۶ میلی‌متر (کابل ۲ زوج یا ۳ زوج دزدگیری) استفاده کنید تا نویزهای الکتریکی محیط روی زون‌ها تأثیر منفی نگذارند.

### ۳. نحوه تست زون:
پس از اتصال، با بستن درب قاب چشمی و حرکت در زاویه دید، ال‌ای‌دی زون مربوطه روی پنل باید روشن شود و در صورت فعال بودن سیستم، آژیر کشیده و پیامک زون ارسال گردد.`,
    contentEn: `Proper wiring of PIR motion sensors is crucial for reliable, false-alarm-free security installations. Learn terminal functions (+, -, NC, Tamper) and wiring standards.`,
    readTime: '۶ دقیقه',
    readTimeEn: '6 min read',
    date: '۱۴۰۳/۱۱/۲۸',
    author: 'تیم مهندسی الفیفای',
    image: '/example_product.webp',
    tags: ['آموزش نصب', 'سیم کشی چشمی', 'دزدگیر اماکن', 'سنسور PIR'],
    category: 'آموزش‌های فنی و نصب',
  },
  {
    id: 'art-2',
    slug: 'compare-best-iranian-alarm-systems-silex-firewall-classic-anik',
    title: 'مقایسه جامع بهترین دزدگیرهای اماکن ایران: سایلکس، فایروال، کلاسیک و ioMax',
    titleEn: 'Ultimate Comparison: Top Iranian Security Alarms (Silex, Firewall, Classic & ioMax)',
    excerpt: 'بررسی تخصصی نقاط قوت، ضعف، سرعت ارسال پیامک، تعداد رله‌های خروجی و گارانتی معتبرترین برندهای دزدگیر ساختمان.',
    excerptEn: 'Deep architectural comparison of reliability, SMS speed, IoT features, and warranties of leading security panels.',
    content: `انتخاب دزدگیر مناسب به متراژ، کاربری (منزل، مغازه، انبار، باغ) و نیاز به اینترنت اشیاء بستگی دارد.

### ۱. پنل‌های ioMax-Plus (نسل جدید با معماری اینترنت اشیاء):
- **نقاط قوت:** پردازش ابری، اپلیکیشن سریع، ۲ تا ۴ رله هوشمند جهت کنترل وسایل برقی، ارسال گزارش زیر ۲ ثانیه.
- **مناسب برای:** منازل مسکونی، باغ و ویلاهایی که نیاز به کنترل پمپ آب و روشنایی دارند.

### ۲. سایلکس مدل SG8-S:
- **نقاط قوت:** تلفن‌کننده سخنگوی بسیار دقیق، مدار سخت‌افزاری بسیار پایدار، تفکیک زون‌ها.
- **مناسب برای:** فروشگاه‌ها، دفاتر اداری و آپارتمان‌ها.

### ۳. فایروال F10:
- **نقاط قوت:** ۸ زون باسیم و ۷ رله خروجی مستقل، گارانتی ۵ ساله معتبر.
- **مناسب برای:** کارگاه‌ها و پروژه‌هایی با تعداد سنسور بالا.

### ۴. کلاسیک Z4 Ultra:
- **نقاط قوت:** امنیت بی‌رقیب ریموت‌های ۶۴ بیتی ترارکد با سابقه طولانی در بازار ایران.`,
    contentEn: `A comprehensive side-by-side comparison between ioMax IoT alarms, Silex SG8-S, Firewall F10, and Classic Z4 Ultra.`,
    readTime: '۸ دقیقه',
    readTimeEn: '8 min read',
    date: '۱۴۰۳/۱۱/۲۰',
    author: 'واحد تحقیق و توسعه الفیفای',
    image: '/example_product.webp',
    tags: ['راهنمای خرید', 'مقایسه دزدگیر', 'سایلکس', 'فایروال', 'کلاسیک'],
    category: 'راهنمای خرید و مقایسه',
  },
  {
    id: 'art-3',
    slug: 'why-does-alarm-trigger-false-alarms-at-night',
    title: 'علت آژیر زدن بی‌دلیل دزدگیر اماکن در شب و روش‌های رفع خطای چشمی',
    titleEn: 'Why Does Alarm Trigger False Alarms at Night and How to Fix It',
    excerpt: 'شناسایی و رفع دلایل اصلی بوق زدن و تحریک ناخواسته چشمی‌ها شامل باد کولر، حشرات، افت ولتاژ باتری و تابش نور مستقیم.',
    excerptEn: 'Troubleshoot common false alarm triggers: temperature swings, insects, low battery voltage, and wind draughts.',
    content: `آژیر کاذب یکی از آزاردهنده‌ترین اتفاقات در سیستم‌های حفاظتی است.

### مهم‌ترین دلایل آژیر کاذب:
1. **افت ولتاژ باتری پشتیبان:** وقتی باتری خراب یا کهنه باشد، در ساعات پایانی شب ولتاژ افت کرده و رله‌های پنل یا چشمی قطع و وصل می‌شوند.
2. **عبور جوندگان و حشرات:** اگر چشمی معمولی روبه‌روی سوراخ‌ها یا منافذ باشد، عبور مارمولک یا موش آژیر را فعال می‌کند. راه حل: استفاده از چشمی‌های وزنی (Pet Immune).
3. **جریان هوای ناگهانی یا دریچه کولر:** تغییر سریع دمای هوای اتاق حسگر مادون قرمز را تحریک می‌کند. چشمی نباید مستقیم به سمت پنجره یا دهانه کولر نصب شود.
4. **شل بودن اتصالات سیم‌کشی:** پیچ‌های شل شده در ترمینال‌ها در اثر لرزش نویز ایجاد می‌کنند.`,
    contentEn: `Learn the top 4 causes of false alarms: aged batteries, rodents, thermal airflow drafts, and loose wiring screw connections.`,
    readTime: '۵ دقیقه',
    readTimeEn: '5 min read',
    date: '۱۴۰۳/۱۱/۱۲',
    author: 'پشتیبانی فنی الفیفای',
    image: '/example_product.webp',
    tags: ['عیب یابی', 'آژیر کاذب', 'تعمیرات دزدگیر', 'باتری'],
    category: 'آموزش‌های فنی و نصب',
  },
];

export const FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'آیا دزدگیرهای سیم‌کارتی الفیفای در صورت قطع برق شهر به کار خود ادامه می‌دهند؟',
    questionEn: 'Do GSM alarm systems continue functioning during a power blackout?',
    answer: 'بله، تمامی پنل‌های دزدگیر ارائه شده در فروشگاه الفیفای مجهز به منبع تغذیه شارژر و جایگاه باتری پشتیبان ۱۲ ولت هستند. در صورت قطع برق، دستگاه بدون یک ثانیه خاموشی به کار خود ادامه داده و بلافاصله پیامک هشدار قطع برق شهر را برای مدیران ارسال می‌کند.',
    answerEn: 'Yes, all ELFify security hubs include intelligent battery charging systems and 12V SLA backup batteries, sending real-time SMS alerts immediately when AC power fails.',
    category: 'general',
  },
  {
    id: 'faq-2',
    question: 'تفاوت چشمی وزنی (Pet-Immune) با چشمی ساده چیست؟',
    questionEn: 'What is the difference between a Pet-Immune sensor and a standard PIR detector?',
    answer: 'چشمی‌های وزنی با بهره‌گیری از ۲ یا ۳ سنسور تفکیک‌کننده، حجم و الگوی حرارتی موجودات زیر ۲۰ الی ۳۰ کیلوگرم (مانند گربه، سگ، پرندگان و خزندگان) را نادیده می‌گیرند و از آژیرهای خطای شبانه به طور ۱۰۰٪ جلوگیری می‌کنند.',
    answerEn: 'Pet-immune sensors utilize multi-element pyroelectric analysis to ignore thermal mass under 20-30kg, completely preventing nuisance false alarms from pets.',
    category: 'installation',
  },
  {
    id: 'faq-3',
    question: 'شرایط گارانتی و خدمات پس از فروش محصولات الفیفای چگونه است؟',
    questionEn: 'What are ELFify product warranties and after-sales support terms?',
    answer: 'تمامی پنل‌های مرکزی و سنسورها دارای ۲۴ الی ۶۰ ماه ضمانت تعویض و اصالت کالا، ۱۰ سال خدمات تأمین قطعات و پشتیبانی تلفنی شبانه‌روزی (۲۴/۷) هستند.',
    answerEn: 'All products feature 24 to 60 months direct replacement warranty, 10-year spare parts commitment, and 24/7 dedicated telephone support.',
    category: 'warranty',
  },
  {
    id: 'faq-4',
    question: 'چگونه می‌توان با رله‌های اینترنت اشیاء (IoT) وسایل برقی خانه یا باغ را از راه دور روشن/خاموش کرد؟',
    questionEn: 'How do IoT smart relays enable remote home & appliance control?',
    answer: 'با اتصال فاز وسیله برقی (نظیر پمپ آب، روشنایی یا شیر برقی گاز) به کنتاکت رله دزدگیر یا ماژول‌های اینترنت اشیاء، می‌توانید از طریق اپلیکیشن موبایل یا ارسال پیامک، در هر لحظه وضعیت رله را تغییر داده یا جدول زمان‌بندی تعریف نمایید.',
    answerEn: 'By connecting appliances to the isolated relay contacts, you can toggle power, set schedules, or trigger automation routines via the smartphone app or SMS commands.',
    category: 'iot',
  },
];
